# Generated by Django 4.0 on 2022-02-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lists.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descriptions', models.TextField()),
                ('Initial_price', models.IntegerField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(default=None, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='list_category', to='lists.Category')),
                ('created_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('list_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.list')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
    ]
