# Generated by Django 4.0 on 2022-02-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='list_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='list_comment', to='lists.list'),
        ),
    ]
