# Generated by Django 4.0 on 2022-02-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('lists', '0003_alter_list_created_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bid_list', to='lists.list')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
    ]
